direction: left

aoi: AllOverIt
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-lib-group: ""
amazon-cdk-lib-group.amazon-cdk-lib_2-147-3: Amazon.CDK.Lib\nv2.147.3
amazon-cdk-lib-group.amazon-cdk-lib_2-147-3.style.fill: "#ADD8E6"
amazon-cdk-lib-group.amazon-cdk-lib_2-147-3.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-202: Amazon.CDK.Asset.AwsCliV1\nv2.2.202
amazon-cdk-asset-awscliv1_2-2-202.style.fill: "#FFEC96"
amazon-cdk-asset-awscliv1_2-2-202.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-202 <- amazon-cdk-lib-group.amazon-cdk-lib_2-147-3
amazon-cdk-asset-kubectlv20_2-1-2: Amazon.CDK.Asset.KubectlV20\nv2.1.2
amazon-cdk-asset-kubectlv20_2-1-2.style.fill: "#FFEC96"
amazon-cdk-asset-kubectlv20_2-1-2.style.opacity: 0.8
amazon-cdk-asset-kubectlv20_2-1-2 <- amazon-cdk-lib-group.amazon-cdk-lib_2-147-3
amazon-cdk-asset-nodeproxyagentv6_2-0-3: Amazon.CDK.Asset.NodeProxyAgentV6\nv2.0.3
amazon-cdk-asset-nodeproxyagentv6_2-0-3.style.fill: "#FFEC96"
amazon-cdk-asset-nodeproxyagentv6_2-0-3.style.opacity: 0.8
amazon-cdk-asset-nodeproxyagentv6_2-0-3 <- amazon-cdk-lib-group.amazon-cdk-lib_2-147-3
amazon-jsii-runtime-group: ""
amazon-jsii-runtime-group.amazon-jsii-runtime_1-99-0: Amazon.JSII.Runtime\nv1.99.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-99-0.style.fill: "#FFEC96"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-99-0.style.opacity: 0.8
amazon-jsii-runtime-group.amazon-jsii-runtime_1-99-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-147-3
constructs-group: ""
constructs-group.constructs_10-0-0: Constructs\nv10.0.0
constructs-group.constructs_10-0-0.style.fill: "#FFEC96"
constructs-group.constructs_10-0-0.style.opacity: 0.8
constructs-group.constructs_10-0-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-147-3
amazon-cdk-lib-group.amazon-cdk-lib_2-147-3 <- aoi.alloverit-aws-cdk-appsync
cdklabs-awscdkappsyncutils_0-0-473: Cdklabs.AwsCdkAppsyncUtils\nv0.0.473
cdklabs-awscdkappsyncutils_0-0-473.style.fill: "#ADD8E6"
cdklabs-awscdkappsyncutils_0-0-473.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0: Amazon.CDK.Lib\nv2.110.0
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.fill: "#FFEC96"
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0 <- cdklabs-awscdkappsyncutils_0-0-473
amazon-jsii-runtime-group.amazon-jsii-runtime_1-101-0: Amazon.JSII.Runtime\nv1.101.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-101-0.style.fill: "#FFEC96"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-101-0.style.opacity: 0.8
amazon-jsii-runtime-group.amazon-jsii-runtime_1-101-0 <- cdklabs-awscdkappsyncutils_0-0-473
constructs-group.constructs_10-0-5: Constructs\nv10.0.5
constructs-group.constructs_10-0-5.style.fill: "#FFEC96"
constructs-group.constructs_10-0-5.style.opacity: 0.8
constructs-group.constructs_10-0-5 <- cdklabs-awscdkappsyncutils_0-0-473
cdklabs-awscdkappsyncutils_0-0-473 <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
