direction: left

aoi: AllOverIt
aoi.alloverit-aws-appsync-client: AllOverIt.Aws.AppSync.Client
microsoft-extensions-dependencyinjection_8-0-0: Microsoft.Extensions.DependencyInjection\nv8.0.0
microsoft-extensions-dependencyinjection_8-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection_8-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_8-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv8.0.0
microsoft-extensions-dependencyinjection-abstractions_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions_8-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_8-0-0 <- microsoft-extensions-dependencyinjection_8-0-0
microsoft-extensions-dependencyinjection_8-0-0 <- aoi.alloverit-aws-appsync-client
microsoft-extensions-http_8-0-0: Microsoft.Extensions.Http\nv8.0.0
microsoft-extensions-http_8-0-0.style.fill: "#ADD8E6"
microsoft-extensions-http_8-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_8-0-0: Microsoft.Extensions.Configuration.Abstractions\nv8.0.0
microsoft-extensions-configuration-abstractions_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_8-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_8-0-0 <- microsoft-extensions-http_8-0-0
microsoft-extensions-dependencyinjection-abstractions_8-0-0 <- microsoft-extensions-http_8-0-0
microsoft-extensions-logging-abstractions_8-0-0: Microsoft.Extensions.Logging.Abstractions\nv8.0.0
microsoft-extensions-logging-abstractions_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions_8-0-0.style.opacity: 0.8
microsoft-extensions-logging-abstractions_8-0-0 <- microsoft-extensions-http_8-0-0
microsoft-extensions-logging_8-0-0: Microsoft.Extensions.Logging\nv8.0.0
microsoft-extensions-logging_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging_8-0-0.style.opacity: 0.8
microsoft-extensions-logging_8-0-0 <- microsoft-extensions-http_8-0-0
microsoft-extensions-options_8-0-0: Microsoft.Extensions.Options\nv8.0.0
microsoft-extensions-options_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-options_8-0-0.style.opacity: 0.8
microsoft-extensions-options_8-0-0 <- microsoft-extensions-http_8-0-0
microsoft-extensions-http_8-0-0 <- aoi.alloverit-aws-appsync-client
aoi.alloverit-reactive: AllOverIt.Reactive
system-reactive_6-0-1: System.Reactive\nv6.0.1
system-reactive_6-0-1.style.fill: "#ADD8E6"
system-reactive_6-0-1.style.opacity: 0.8
system-reactive_6-0-1 <- aoi.alloverit-reactive
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactive
aoi.alloverit-reactive <- aoi.alloverit-aws-appsync-client
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-aws-appsync-client
