direction: left

aoi: AllOverIt
aoi.alloverit-validation-options: AllOverIt.Validation.Options
microsoft-extensions-options_8-0-2: Microsoft.Extensions.Options\nv8.0.2
microsoft-extensions-options_8-0-2.style.fill: "#ADD8E6"
microsoft-extensions-options_8-0-2.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_8-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv8.0.0
microsoft-extensions-dependencyinjection-abstractions_8-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_8-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_8-0-0 <- microsoft-extensions-options_8-0-2
microsoft-extensions-primitives_8-0-0: Microsoft.Extensions.Primitives\nv8.0.0
microsoft-extensions-primitives_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-primitives_8-0-0.style.opacity: 0.8
microsoft-extensions-primitives_8-0-0 <- microsoft-extensions-options_8-0-2
microsoft-extensions-options_8-0-2 <- aoi.alloverit-validation-options
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation_11-9-0: FluentValidation\nv11.9.0
fluentvalidation_11-9-0.style.fill: "#ADD8E6"
fluentvalidation_11-9-0.style.opacity: 0.8
fluentvalidation_11-9-0 <- aoi.alloverit-validation
microsoft-extensions-dependencyinjection-abstractions_8-0-0 <- aoi.alloverit-validation
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-validation
aoi.alloverit-validation <- aoi.alloverit-validation-options
