direction: left

aoi: AllOverIt
aoi.alloverit-serialization-json-systemtext: AllOverIt.Serialization.Json.SystemText
system-text-json_8-0-0: System.Text.Json\nv8.0.0
system-text-json_8-0-0.style.fill: "#ADD8E6"
system-text-json_8-0-0.style.opacity: 0.8
system-text-encodings-web_8-0-0: System.Text.Encodings.Web\nv8.0.0
system-text-encodings-web_8-0-0.style.fill: "#FFEC96"
system-text-encodings-web_8-0-0.style.opacity: 0.8
system-text-encodings-web_8-0-0 <- system-text-json_8-0-0
system-runtime-compilerservices-unsafe_6-0-0: System.Runtime.CompilerServices.Unsafe\nv6.0.0
system-runtime-compilerservices-unsafe_6-0-0.style.fill: "#FFEC96"
system-runtime-compilerservices-unsafe_6-0-0.style.opacity: 0.8
system-runtime-compilerservices-unsafe_6-0-0 <- system-text-json_8-0-0
system-text-json_8-0-0 <- aoi.alloverit-serialization-json-systemtext
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-systemtext
