direction: left

aoi: AllOverIt
aoi.alloverit-reactiveui-wpf: AllOverIt.ReactiveUI.Wpf
reactiveui-wpf_20-0-1: ReactiveUI.WPF\nv20.0.1
reactiveui-wpf_20-0-1.style.fill: "#ADD8E6"
reactiveui-wpf_20-0-1.style.opacity: 0.8
reactiveui-wpf_20-0-1 <- aoi.alloverit-reactiveui-wpf
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
microsoft-extensions-dependencyinjection-abstractions_8-0-1: Microsoft.Extensions.DependencyInjection.Abstractions\nv8.0.1
microsoft-extensions-dependencyinjection-abstractions_8-0-1.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_8-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_8-0-1 <- aoi.alloverit-reactiveui
reactiveui_20-0-1: ReactiveUI\nv20.0.1
reactiveui_20-0-1.style.fill: "#ADD8E6"
reactiveui_20-0-1.style.opacity: 0.8
dynamicdata_8-4-1: DynamicData\nv8.4.1
dynamicdata_8-4-1.style.fill: "#FFEC96"
dynamicdata_8-4-1.style.opacity: 0.8
dynamicdata_8-4-1 <- reactiveui_20-0-1
splat_15-0-1: Splat\nv15.0.1
splat_15-0-1.style.fill: "#FFEC96"
splat_15-0-1.style.opacity: 0.8
splat_15-0-1 <- reactiveui_20-0-1
system-componentmodel-annotations_5-0-0: System.ComponentModel.Annotations\nv5.0.0
system-componentmodel-annotations_5-0-0.style.fill: "#FFEC96"
system-componentmodel-annotations_5-0-0.style.opacity: 0.8
system-componentmodel-annotations_5-0-0 <- reactiveui_20-0-1
system-text-json_8-0-3: System.Text.Json\nv8.0.3
system-text-json_8-0-3.style.fill: "#FFEC96"
system-text-json_8-0-3.style.opacity: 0.8
system-text-json_8-0-3 <- reactiveui_20-0-1
reactiveui_20-0-1 <- aoi.alloverit-reactiveui
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactiveui
aoi.alloverit-reactiveui <- aoi.alloverit-reactiveui-wpf
