direction: left

aoi: AllOverIt
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation_12-0-0: FluentValidation\nv12.0.0
fluentvalidation_12-0-0.style.fill: "#ADD8E6"
fluentvalidation_12-0-0.style.opacity: 0.8
fluentvalidation_12-0-0 <- aoi.alloverit-validation
microsoft-extensions-dependencyinjection-abstractions_9-0-8: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-8.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_9-0-8.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-8 <- aoi.alloverit-validation
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-validation
