direction: left

aoi: AllOverIt
aoi.alloverit-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
microsoft-entityframeworkcore-relational_8-0-1: Microsoft.EntityFrameworkCore.Relational\nv8.0.1
microsoft-entityframeworkcore-relational_8-0-1.style.fill: "#ADD8E6"
microsoft-entityframeworkcore-relational_8-0-1.style.opacity: 0.8
microsoft-entityframeworkcore_8-0-1: Microsoft.EntityFrameworkCore\nv8.0.1
microsoft-entityframeworkcore_8-0-1.style.fill: "#FFEC96"
microsoft-entityframeworkcore_8-0-1.style.opacity: 0.8
microsoft-entityframeworkcore_8-0-1 <- microsoft-entityframeworkcore-relational_8-0-1
microsoft-extensions-configuration-abstractions_8-0-0: Microsoft.Extensions.Configuration.Abstractions\nv8.0.0
microsoft-extensions-configuration-abstractions_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_8-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_8-0-0 <- microsoft-entityframeworkcore-relational_8-0-1
microsoft-entityframeworkcore-relational_8-0-1 <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-entityframeworkcore-diagrams
