direction: left

aoi: AllOverIt
aoi.alloverit-csv: AllOverIt.Csv
csvhelper_30-1-0: CsvHelper\nv30.1.0
csvhelper_30-1-0.style.fill: "#ADD8E6"
csvhelper_30-1-0.style.opacity: 0.8
system-linq-async_4-0-0: System.Linq.Async\nv4.0.0
system-linq-async_4-0-0.style.fill: "#FFEC96"
system-linq-async_4-0-0.style.opacity: 0.8
system-linq-async_4-0-0 <- csvhelper_30-1-0
csvhelper_30-1-0 <- aoi.alloverit-csv
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-csv
