direction: left

aoi: AllOverIt
aoi.alloverit-dependencyinjection: AllOverIt.DependencyInjection
microsoft-extensions-dependencyinjection-abstractions_9-0-3: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.3
microsoft-extensions-dependencyinjection-abstractions_9-0-3.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_9-0-3.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-3 <- aoi.alloverit-dependencyinjection
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-dependencyinjection
