direction: left

aoi: AllOverIt
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit-aspnetcore: AllOverIt.AspNetCore
aoi.alloverit <- aoi.alloverit-aspnetcore
aoi.alloverit-aws-appsync-client: AllOverIt.Aws.AppSync.Client
aoi.alloverit-reactive: AllOverIt.Reactive
aoi.alloverit <- aoi.alloverit-reactive
aoi.alloverit-reactive <- aoi.alloverit-aws-appsync-client
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-aws-appsync-client
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit-cryptography: AllOverIt.Cryptography
aoi.alloverit <- aoi.alloverit-cryptography
aoi.alloverit-csv: AllOverIt.Csv
aoi.alloverit <- aoi.alloverit-csv
aoi.alloverit-dependencyinjection: AllOverIt.DependencyInjection
aoi.alloverit <- aoi.alloverit-dependencyinjection
aoi.alloverit-entityframeworkcore: AllOverIt.EntityFrameworkCore
aoi.alloverit <- aoi.alloverit-entityframeworkcore
aoi.alloverit-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
aoi.alloverit <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit-entityframeworkcore-pagination: AllOverIt.EntityFrameworkCore.Pagination
aoi.alloverit-entityframeworkcore <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-pagination: AllOverIt.Pagination
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit-serialization-binary <- aoi.alloverit-pagination
aoi.alloverit-pagination <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-evaluator: AllOverIt.Evaluator
aoi.alloverit <- aoi.alloverit-evaluator
aoi.alloverit-filtering: AllOverIt.Filtering
aoi.alloverit <- aoi.alloverit-filtering
aoi.alloverit-fixture: AllOverIt.Fixture
aoi.alloverit-fixture-fakeiteasy: AllOverIt.Fixture.FakeItEasy
aoi.alloverit-fixture <- aoi.alloverit-fixture-fakeiteasy
aoi.alloverit-generichost: AllOverIt.GenericHost
aoi.alloverit <- aoi.alloverit-generichost
aoi.alloverit-logging: AllOverIt.Logging
aoi.alloverit <- aoi.alloverit-logging
aoi.alloverit-logging-testing: AllOverIt.Logging.Testing
aoi.alloverit-logging <- aoi.alloverit-logging-testing
aoi.alloverit-mapping: AllOverIt.Mapping
aoi.alloverit <- aoi.alloverit-mapping
aoi.alloverit-pipes: AllOverIt.Pipes
aoi.alloverit-serialization-binary <- aoi.alloverit-pipes
aoi.alloverit-reactive <- aoi.alloverit-pipes
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
aoi.alloverit <- aoi.alloverit-reactiveui
aoi.alloverit-reactiveui-wpf: AllOverIt.ReactiveUI.Wpf
aoi.alloverit-reactiveui <- aoi.alloverit-reactiveui-wpf
aoi.alloverit-serialization-json-newtonsoft: AllOverIt.Serialization.Json.Newtonsoft
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-newtonsoft
aoi.alloverit-serialization-json-systemtext: AllOverIt.Serialization.Json.SystemText
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-systemtext
aoi.alloverit-serilog: AllOverIt.Serilog
aoi.alloverit <- aoi.alloverit-serilog
aoi.alloverit-validation: AllOverIt.Validation
aoi.alloverit <- aoi.alloverit-validation
aoi.alloverit-validation-options: AllOverIt.Validation.Options
aoi.alloverit-validation <- aoi.alloverit-validation-options
aoi.alloverit-wpf: AllOverIt.Wpf
aoi.alloverit <- aoi.alloverit-wpf
aoi.alloverit-wpf-controls: AllOverIt.Wpf.Controls
aoi.alloverit <- aoi.alloverit-wpf-controls
