direction: left

aoi: AllOverIt
aoi.alloverit-validation-options: AllOverIt.Validation.Options
microsoft-extensions-options_9-0-3: Microsoft.Extensions.Options\nv9.0.3
microsoft-extensions-options_9-0-3.style.fill: "#ADD8E6"
microsoft-extensions-options_9-0-3.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-3: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.3
microsoft-extensions-dependencyinjection-abstractions_9-0-3.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-3.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_9-0-3 <- microsoft-extensions-options_9-0-3
microsoft-extensions-primitives_9-0-3: Microsoft.Extensions.Primitives\nv9.0.3
microsoft-extensions-primitives_9-0-3.style.fill: "#FFEC96"
microsoft-extensions-primitives_9-0-3.style.opacity: 0.8
microsoft-extensions-primitives_9-0-3 <- microsoft-extensions-options_9-0-3
microsoft-extensions-options_9-0-3 <- aoi.alloverit-validation-options
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation_11-11-0: FluentValidation\nv11.11.0
fluentvalidation_11-11-0.style.fill: "#ADD8E6"
fluentvalidation_11-11-0.style.opacity: 0.8
fluentvalidation_11-11-0 <- aoi.alloverit-validation
microsoft-extensions-dependencyinjection-abstractions_9-0-3 <- aoi.alloverit-validation
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-validation
aoi.alloverit-validation <- aoi.alloverit-validation-options
