direction: left

aoi: AllOverIt
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-lib-group: ""
amazon-cdk-lib-group.amazon-cdk-lib_2-211-0: Amazon.CDK.Lib\nv2.211.0
amazon-cdk-lib-group.amazon-cdk-lib_2-211-0.style.fill: "#ADD8E6"
amazon-cdk-lib-group.amazon-cdk-lib_2-211-0.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-242: Amazon.CDK.Asset.AwsCliV1\nv2.2.242
amazon-cdk-asset-awscliv1_2-2-242.style.fill: "#FFEC96"
amazon-cdk-asset-awscliv1_2-2-242.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-242 <- amazon-cdk-lib-group.amazon-cdk-lib_2-211-0
amazon-cdk-asset-nodeproxyagentv6_2-1-0: Amazon.CDK.Asset.NodeProxyAgentV6\nv2.1.0
amazon-cdk-asset-nodeproxyagentv6_2-1-0.style.fill: "#FFEC96"
amazon-cdk-asset-nodeproxyagentv6_2-1-0.style.opacity: 0.8
amazon-cdk-asset-nodeproxyagentv6_2-1-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-211-0
amazon-cdk-cloudassembly-schema_48-2-0: Amazon.CDK.CloudAssembly.Schema\nv48.2.0
amazon-cdk-cloudassembly-schema_48-2-0.style.fill: "#FFEC96"
amazon-cdk-cloudassembly-schema_48-2-0.style.opacity: 0.8
amazon-cdk-cloudassembly-schema_48-2-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-211-0
amazon-jsii-runtime_1-113-0: Amazon.JSII.Runtime\nv1.113.0
amazon-jsii-runtime_1-113-0.style.fill: "#FFEC96"
amazon-jsii-runtime_1-113-0.style.opacity: 0.8
amazon-jsii-runtime_1-113-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-211-0
constructs-group: ""
constructs-group.constructs_10-0-0: Constructs\nv10.0.0
constructs-group.constructs_10-0-0.style.fill: "#FFEC96"
constructs-group.constructs_10-0-0.style.opacity: 0.8
constructs-group.constructs_10-0-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-211-0
amazon-cdk-lib-group.amazon-cdk-lib_2-211-0 <- aoi.alloverit-aws-cdk-appsync
cdklabs-awscdkappsyncutils_0-0-805: Cdklabs.AwsCdkAppsyncUtils\nv0.0.805
cdklabs-awscdkappsyncutils_0-0-805.style.fill: "#ADD8E6"
cdklabs-awscdkappsyncutils_0-0-805.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0: Amazon.CDK.Lib\nv2.110.0
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.fill: "#FFEC96"
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0 <- cdklabs-awscdkappsyncutils_0-0-805
amazon-jsii-runtime_1-113-0 <- cdklabs-awscdkappsyncutils_0-0-805
constructs-group.constructs_10-0-5: Constructs\nv10.0.5
constructs-group.constructs_10-0-5.style.fill: "#FFEC96"
constructs-group.constructs_10-0-5.style.opacity: 0.8
constructs-group.constructs_10-0-5 <- cdklabs-awscdkappsyncutils_0-0-805
cdklabs-awscdkappsyncutils_0-0-805 <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
