direction: left

aoi: AllOverIt
aoi.alloverit-serilog: AllOverIt.Serilog
microsoft-extensions-dependencyinjection-abstractions-group: ""
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.0
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0 <- aoi.alloverit-serilog
microsoft-extensions-hosting-abstractions-group: ""
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0: Microsoft.Extensions.Hosting.Abstractions\nv9.0.0
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0.style.fill: "#ADD8E6"
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_9-0-0: Microsoft.Extensions.Configuration.Abstractions\nv9.0.0
microsoft-extensions-configuration-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_9-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0
microsoft-extensions-diagnostics-abstractions_9-0-0: Microsoft.Extensions.Diagnostics.Abstractions\nv9.0.0
microsoft-extensions-diagnostics-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-diagnostics-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-diagnostics-abstractions_9-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0
microsoft-extensions-fileproviders-abstractions_9-0-0: Microsoft.Extensions.FileProviders.Abstractions\nv9.0.0
microsoft-extensions-fileproviders-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-fileproviders-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-fileproviders-abstractions_9-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0
microsoft-extensions-logging-abstractions-group: ""
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_9-0-0: Microsoft.Extensions.Logging.Abstractions\nv9.0.0
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_9-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0 <- aoi.alloverit-serilog
serilog-extensions-hosting_8-0-0: Serilog.Extensions.Hosting\nv8.0.0
serilog-extensions-hosting_8-0-0.style.fill: "#ADD8E6"
serilog-extensions-hosting_8-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_8-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv8.0.0
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_8-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_8-0-0 <- serilog-extensions-hosting_8-0-0
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_8-0-0: Microsoft.Extensions.Hosting.Abstractions\nv8.0.0
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_8-0-0.style.opacity: 0.8
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_8-0-0 <- serilog-extensions-hosting_8-0-0
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_8-0-0: Microsoft.Extensions.Logging.Abstractions\nv8.0.0
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_8-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_8-0-0.style.opacity: 0.8
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_8-0-0 <- serilog-extensions-hosting_8-0-0
serilog_3-1-1: Serilog\nv3.1.1
serilog_3-1-1.style.fill: "#FFEC96"
serilog_3-1-1.style.opacity: 0.8
serilog_3-1-1 <- serilog-extensions-hosting_8-0-0
serilog-extensions-logging_8-0-0: Serilog.Extensions.Logging\nv8.0.0
serilog-extensions-logging_8-0-0.style.fill: "#FFEC96"
serilog-extensions-logging_8-0-0.style.opacity: 0.8
serilog-extensions-logging_8-0-0 <- serilog-extensions-hosting_8-0-0
serilog-extensions-hosting_8-0-0 <- aoi.alloverit-serilog
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-serilog
