direction: left

aoi: AllOverIt
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
microsoft-extensions-dependencyinjection-abstractions_9-0-8: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-8.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_9-0-8.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-8 <- aoi.alloverit-reactiveui
reactiveui_20-4-1: ReactiveUI\nv20.4.1
reactiveui_20-4-1.style.fill: "#ADD8E6"
reactiveui_20-4-1.style.opacity: 0.8
dynamicdata_9-4-1: DynamicData\nv9.4.1
dynamicdata_9-4-1.style.fill: "#FFEC96"
dynamicdata_9-4-1.style.opacity: 0.8
dynamicdata_9-4-1 <- reactiveui_20-4-1
splat_15-3-1: Splat\nv15.3.1
splat_15-3-1.style.fill: "#FFEC96"
splat_15-3-1.style.opacity: 0.8
splat_15-3-1 <- reactiveui_20-4-1
system-componentmodel-annotations_5-0-0: System.ComponentModel.Annotations\nv5.0.0
system-componentmodel-annotations_5-0-0.style.fill: "#FFEC96"
system-componentmodel-annotations_5-0-0.style.opacity: 0.8
system-componentmodel-annotations_5-0-0 <- reactiveui_20-4-1
reactiveui_20-4-1 <- aoi.alloverit-reactiveui
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactiveui
