direction: left

aoi: AllOverIt
aoi.alloverit-logging-testing: AllOverIt.Logging.Testing
fluentassertions_7-1-0: FluentAssertions\nv7.1.0
fluentassertions_7-1-0.style.fill: "#ADD8E6"
fluentassertions_7-1-0.style.opacity: 0.8
system-configuration-configurationmanager_6-0-0: System.Configuration.ConfigurationManager\nv6.0.0
system-configuration-configurationmanager_6-0-0.style.fill: "#FFEC96"
system-configuration-configurationmanager_6-0-0.style.opacity: 0.8
system-configuration-configurationmanager_6-0-0 <- fluentassertions_7-1-0
fluentassertions_7-1-0 <- aoi.alloverit-logging-testing
nsubstitute_5-3-0: NSubstitute\nv5.3.0
nsubstitute_5-3-0.style.fill: "#ADD8E6"
nsubstitute_5-3-0.style.opacity: 0.8
castle-core_5-1-1: Castle.Core\nv5.1.1
castle-core_5-1-1.style.fill: "#FFEC96"
castle-core_5-1-1.style.opacity: 0.8
castle-core_5-1-1 <- nsubstitute_5-3-0
nsubstitute_5-3-0 <- aoi.alloverit-logging-testing
microsoft-extensions-logging-abstractions_9-0-1: Microsoft.Extensions.Logging.Abstractions\nv9.0.1
microsoft-extensions-logging-abstractions_9-0-1.style.fill: "#ADD8E6"
microsoft-extensions-logging-abstractions_9-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-1: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.1
microsoft-extensions-dependencyinjection-abstractions_9-0-1.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions_9-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-1 <- microsoft-extensions-logging-abstractions_9-0-1
system-diagnostics-diagnosticsource_9-0-1: System.Diagnostics.DiagnosticSource\nv9.0.1
system-diagnostics-diagnosticsource_9-0-1.style.fill: "#FFEC96"
system-diagnostics-diagnosticsource_9-0-1.style.opacity: 0.8
system-diagnostics-diagnosticsource_9-0-1 <- microsoft-extensions-logging-abstractions_9-0-1
microsoft-extensions-logging-abstractions_9-0-1 <- aoi.alloverit-logging-testing
aoi.alloverit-logging: AllOverIt.Logging
microsoft-extensions-logging-abstractions_9-0-1 <- aoi.alloverit-logging
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-logging
aoi.alloverit-logging <- aoi.alloverit-logging-testing
