direction: left

aoi: AllOverIt
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
microsoft-extensions-dependencyinjection-abstractions_9-0-1: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.1
microsoft-extensions-dependencyinjection-abstractions_9-0-1.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_9-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-1 <- aoi.alloverit-reactiveui
reactiveui_20-1-63: ReactiveUI\nv20.1.63
reactiveui_20-1-63.style.fill: "#ADD8E6"
reactiveui_20-1-63.style.opacity: 0.8
dynamicdata_9-0-4: DynamicData\nv9.0.4
dynamicdata_9-0-4.style.fill: "#FFEC96"
dynamicdata_9-0-4.style.opacity: 0.8
dynamicdata_9-0-4 <- reactiveui_20-1-63
splat_15-1-1: Splat\nv15.1.1
splat_15-1-1.style.fill: "#FFEC96"
splat_15-1-1.style.opacity: 0.8
splat_15-1-1 <- reactiveui_20-1-63
system-componentmodel-annotations_5-0-0: System.ComponentModel.Annotations\nv5.0.0
system-componentmodel-annotations_5-0-0.style.fill: "#FFEC96"
system-componentmodel-annotations_5-0-0.style.opacity: 0.8
system-componentmodel-annotations_5-0-0 <- reactiveui_20-1-63
reactiveui_20-1-63 <- aoi.alloverit-reactiveui
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactiveui
