flowchart LR
  alloverit-cryptography["AllOverIt.Cryptography"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-cryptography --> alloverit
  alloverit --> alloverit-assertion
