flowchart LR
  alloverit-logging["AllOverIt.Logging"]
  microsoft-extensions-logging-abstractions_9-0-17["Microsoft.Extensions.Logging.Abstractions<br>v9.0.17"]
  microsoft-extensions-dependencyinjection-abstractions_9-0-17["Microsoft.Extensions.DependencyInjection.Abstractions<br>v9.0.17"]
  system-diagnostics-diagnosticsource_9-0-17["System.Diagnostics.DiagnosticSource<br>v9.0.17"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-logging --> microsoft-extensions-logging-abstractions_9-0-17
  microsoft-extensions-logging-abstractions_9-0-17 --> microsoft-extensions-dependencyinjection-abstractions_9-0-17
  microsoft-extensions-logging-abstractions_9-0-17 --> system-diagnostics-diagnosticsource_9-0-17
  alloverit-logging --> alloverit
  alloverit --> alloverit-assertion
  style microsoft-extensions-logging-abstractions_9-0-17 fill:#ADD8E6,opacity:0.8
  style microsoft-extensions-dependencyinjection-abstractions_9-0-17 fill:#FFEC96,opacity:0.8
  style system-diagnostics-diagnosticsource_9-0-17 fill:#FFEC96,opacity:0.8
