flowchart LR
  alloverit-serialization-json-abstractions["AllOverIt.Serialization.Json.Abstractions"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-serialization-json-abstractions --> alloverit
  alloverit --> alloverit-assertion
