flowchart LR
  alloverit-wpf-controls["AllOverIt.Wpf.Controls"]
  microsoft-xaml-behaviors-wpf_1-1-142["Microsoft.Xaml.Behaviors.Wpf<br>v1.1.142"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-wpf-controls --> microsoft-xaml-behaviors-wpf_1-1-142
  alloverit-wpf-controls --> alloverit
  alloverit --> alloverit-assertion
  style microsoft-xaml-behaviors-wpf_1-1-142 fill:#ADD8E6,opacity:0.8
