flowchart LR
  alloverit-serilog["AllOverIt.Serilog"]
  microsoft-extensions-dependencyinjection-abstractions_10-0-8["Microsoft.Extensions.DependencyInjection.Abstractions<br>v10.0.8"]
  microsoft-extensions-hosting-abstractions_10-0-8["Microsoft.Extensions.Hosting.Abstractions<br>v10.0.8"]
  microsoft-extensions-configuration-abstractions_10-0-8["Microsoft.Extensions.Configuration.Abstractions<br>v10.0.8"]
  microsoft-extensions-diagnostics-abstractions_10-0-8["Microsoft.Extensions.Diagnostics.Abstractions<br>v10.0.8"]
  microsoft-extensions-fileproviders-abstractions_10-0-8["Microsoft.Extensions.FileProviders.Abstractions<br>v10.0.8"]
  microsoft-extensions-logging-abstractions_10-0-8["Microsoft.Extensions.Logging.Abstractions<br>v10.0.8"]
  serilog-extensions-hosting_10-0-0["Serilog.Extensions.Hosting<br>v10.0.0"]
  serilog_4-3-0["Serilog<br>v4.3.0"]
  serilog-extensions-logging_10-0-0["Serilog.Extensions.Logging<br>v10.0.0"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-serilog --> microsoft-extensions-dependencyinjection-abstractions_10-0-8
  alloverit-serilog --> microsoft-extensions-hosting-abstractions_10-0-8
  microsoft-extensions-hosting-abstractions_10-0-8 --> microsoft-extensions-configuration-abstractions_10-0-8
  microsoft-extensions-hosting-abstractions_10-0-8 --> microsoft-extensions-dependencyinjection-abstractions_10-0-8
  microsoft-extensions-hosting-abstractions_10-0-8 --> microsoft-extensions-diagnostics-abstractions_10-0-8
  microsoft-extensions-hosting-abstractions_10-0-8 --> microsoft-extensions-fileproviders-abstractions_10-0-8
  microsoft-extensions-hosting-abstractions_10-0-8 --> microsoft-extensions-logging-abstractions_10-0-8
  alloverit-serilog --> serilog-extensions-hosting_10-0-0
  serilog-extensions-hosting_10-0-0 --> microsoft-extensions-dependencyinjection-abstractions_10-0-8
  serilog-extensions-hosting_10-0-0 --> microsoft-extensions-hosting-abstractions_10-0-8
  serilog-extensions-hosting_10-0-0 --> microsoft-extensions-logging-abstractions_10-0-8
  serilog-extensions-hosting_10-0-0 --> serilog_4-3-0
  serilog-extensions-hosting_10-0-0 --> serilog-extensions-logging_10-0-0
  alloverit-serilog --> alloverit
  alloverit --> alloverit-assertion
  style microsoft-extensions-dependencyinjection-abstractions_10-0-8 fill:#ADD8E6,opacity:0.8
  style microsoft-extensions-hosting-abstractions_10-0-8 fill:#ADD8E6,opacity:0.8
  style microsoft-extensions-configuration-abstractions_10-0-8 fill:#FFEC96,opacity:0.8
  style microsoft-extensions-diagnostics-abstractions_10-0-8 fill:#FFEC96,opacity:0.8
  style microsoft-extensions-fileproviders-abstractions_10-0-8 fill:#FFEC96,opacity:0.8
  style microsoft-extensions-logging-abstractions_10-0-8 fill:#FFEC96,opacity:0.8
  style serilog-extensions-hosting_10-0-0 fill:#ADD8E6,opacity:0.8
  style serilog_4-3-0 fill:#FFEC96,opacity:0.8
  style serilog-extensions-logging_10-0-0 fill:#FFEC96,opacity:0.8
