flowchart LR
  alloverit-filtering["AllOverIt.Filtering"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-filtering --> alloverit
  alloverit --> alloverit-assertion
