direction: left

aoi: AllOverIt
aoi.alloverit-cryptography: AllOverIt.Cryptography
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit <- aoi.alloverit-cryptography
aoi.alloverit-assertion <- aoi.alloverit
aoi.style.fill: "#E7EBFC"
aoi.style.opacity: 1

