direction: left

aoi: AllOverIt
aoi.alloverit-csv: AllOverIt.Csv
csvhelper_33-1-0: CsvHelper\nv33.1.0
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
csvhelper_33-1-0 <- aoi.alloverit-csv
aoi.alloverit <- aoi.alloverit-csv
aoi.alloverit-assertion <- aoi.alloverit
csvhelper_33-1-0.style.fill: "#ADD8E6"
csvhelper_33-1-0.style.opacity: 0.8
aoi.style.fill: "#E7EBFC"
aoi.style.opacity: 1

