direction: left

aoi: AllOverIt
aoi.alloverit-wpf: AllOverIt.Wpf
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit <- aoi.alloverit-wpf
aoi.alloverit-assertion <- aoi.alloverit
aoi.style.fill: "#E7EBFC"
aoi.style.opacity: 1

