direction: left

aoi: AllOverIt
aoi.alloverit-logging: AllOverIt.Logging
microsoft-extensions-logging-abstractions_10-0-8: Microsoft.Extensions.Logging.Abstractions\nv10.0.8
microsoft-extensions-dependencyinjection-abstractions_10-0-8: Microsoft.Extensions.DependencyInjection.Abstractions\nv10.0.8
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
microsoft-extensions-logging-abstractions_10-0-8 <- aoi.alloverit-logging
microsoft-extensions-dependencyinjection-abstractions_10-0-8 <- microsoft-extensions-logging-abstractions_10-0-8
aoi.alloverit <- aoi.alloverit-logging
aoi.alloverit-assertion <- aoi.alloverit
microsoft-extensions-logging-abstractions_10-0-8.style.fill: "#ADD8E6"
microsoft-extensions-logging-abstractions_10-0-8.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_10-0-8.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions_10-0-8.style.opacity: 0.8
aoi.style.fill: "#E7EBFC"
aoi.style.opacity: 1

