direction: left

aoi: AllOverIt
aoi.alloverit-mapping: AllOverIt.Mapping
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit <- aoi.alloverit-mapping
aoi.alloverit-assertion <- aoi.alloverit
aoi.style.fill: "#E7EBFC"
aoi.style.opacity: 1

