direction: left

aoi: AllOverIt
aoi.alloverit-reactive: AllOverIt.Reactive
system-reactive_6-1-0: System.Reactive\nv6.1.0
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
system-reactive_6-1-0 <- aoi.alloverit-reactive
aoi.alloverit <- aoi.alloverit-reactive
aoi.alloverit-assertion <- aoi.alloverit
system-reactive_6-1-0.style.fill: "#ADD8E6"
system-reactive_6-1-0.style.opacity: 0.8
aoi.style.fill: "#E7EBFC"
aoi.style.opacity: 1

