direction: right

web: Web

blog: "" {
  style: {
    fill: \#ffd8d8
    stroke: blue
    stroke-width: 4
  }
}

role_perm: Roles / Permissions {
  style: {
    fill: \#ffffcc
    stroke: \#cccc99
  }
}

role_perm.AuthorRole: {
  shape: sql_table

  style: {
    stroke: \#ccffcc
  }

  AuthorsId: INTEGER \[NOT NULL\] {constraint: foreign_key}
  RolesId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

blog.Author: {
  shape: sql_table

  style: {
    fill: black
    stroke: \#99ccff
    stroke-width: 4
    stroke-dash: 2
  }

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  FirstName: TEXT(50) \[NOT NULL\]
  LastName: TEXT(50)
  Email: TEXT(50) \[NOT NULL\]
}

blog.AuthorBlog: {
  shape: sql_table

  style: {
    stroke: \#ccffcc
  }

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  BloggerId: INTEGER \[NOT NULL\] {constraint: foreign_key}
  AuthorId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

blog.Blog: {
  shape: sql_table

  style: {
    fill: black
    stroke: \#99ccff
    stroke-width: 4
    stroke-dash: 2
  }

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  Description: TEXT(500) \[NOT NULL\]
  WebSiteId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

Comment: {
  shape: sql_table

  Id: INTEGER {constraint: primary_key}
  Content: TEXT
  PostId: INTEGER {constraint: foreign_key}
  AuthorId: INTEGER {constraint: foreign_key}
}

role_perm.Permission: {
  shape: sql_table

  style: {
    stroke: \#ccffcc
  }

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  Name: TEXT
}

blog.Post: {
  shape: sql_table

  style: {
    stroke: \#ccffcc
  }

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  Title: TEXT(500) \[NOT NULL\]
  Content: TEXT \[NOT NULL\]
  BlogId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

role_perm.Role: {
  shape: sql_table

  style: {
    stroke: \#ccffcc
  }

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  Name: TEXT
}

web.Settings: {
  shape: sql_table

  style: {
    stroke: \#ccffcc
  }

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  JsonConfig: TEXT \[NOT NULL\]
  WebSiteId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

web.WebSite: {
  shape: sql_table

  style: {
    stroke: \#ccffcc
  }

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  Description: TEXT(500) \[NOT NULL\]
}

role_perm.RolePermission: {
  shape: sql_table

  style: {
    stroke: \#ccffcc
  }

  PermissionsId: INTEGER \[NOT NULL\] {constraint: foreign_key}
  RolesId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

blog.Author.Id <-> role_perm.AuthorRole.AuthorsId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

role_perm.Role.Id <-> role_perm.AuthorRole.RolesId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

blog.Blog.Id <-> blog.AuthorBlog.BloggerId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

blog.Author.Id <-> blog.AuthorBlog.AuthorId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

web.WebSite.Id <-> blog.Blog.WebSiteId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

blog.Post.Id <-> Comment.PostId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

blog.Author.Id <-> Comment.AuthorId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

blog.Blog.Id <-> blog.Post.BlogId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

web.WebSite.Id <-> web.Settings.WebSiteId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-one
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

role_perm.Permission.Id <-> role_perm.RolePermission.PermissionsId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

role_perm.Role.Id <-> role_perm.RolePermission.RolesId: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}
