flowchart LR
  alloverit-evaluator["AllOverIt.Evaluator"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-evaluator --> alloverit
  alloverit --> alloverit-assertion
