flowchart LR
  alloverit-serialization-binary["AllOverIt.Serialization.Binary"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-serialization-binary --> alloverit
  alloverit --> alloverit-assertion
