direction: left

aoi: AllOverIt
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation_11-9-2: FluentValidation\nv11.9.2
fluentvalidation_11-9-2.style.fill: "#ADD8E6"
fluentvalidation_11-9-2.style.opacity: 0.8
fluentvalidation_11-9-2 <- aoi.alloverit-validation
microsoft-extensions-dependencyinjection-abstractions_8-0-1: Microsoft.Extensions.DependencyInjection.Abstractions\nv8.0.1
microsoft-extensions-dependencyinjection-abstractions_8-0-1.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_8-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_8-0-1 <- aoi.alloverit-validation
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-validation
