direction: left

aoi: AllOverIt
aoi.alloverit-csv: AllOverIt.Csv
csvhelper_33-1-0: CsvHelper\nv33.1.0
csvhelper_33-1-0.style.fill: "#ADD8E6"
csvhelper_33-1-0.style.opacity: 0.8
csvhelper_33-1-0 <- aoi.alloverit-csv
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-csv
