direction: left

aoi: AllOverIt
aoi.alloverit-generichost: AllOverIt.GenericHost
microsoft-extensions-hosting_9-0-0: Microsoft.Extensions.Hosting\nv9.0.0
microsoft-extensions-hosting_9-0-0.style.fill: "#ADD8E6"
microsoft-extensions-hosting_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_9-0-0: Microsoft.Extensions.Configuration.Abstractions\nv9.0.0
microsoft-extensions-configuration-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-configuration-binder_9-0-0: Microsoft.Extensions.Configuration.Binder\nv9.0.0
microsoft-extensions-configuration-binder_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-binder_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-binder_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-configuration-commandline_9-0-0: Microsoft.Extensions.Configuration.CommandLine\nv9.0.0
microsoft-extensions-configuration-commandline_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-commandline_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-commandline_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-configuration-environmentvariables_9-0-0: Microsoft.Extensions.Configuration.EnvironmentVariables\nv9.0.0
microsoft-extensions-configuration-environmentvariables_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-environmentvariables_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-environmentvariables_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-configuration-fileextensions_9-0-0: Microsoft.Extensions.Configuration.FileExtensions\nv9.0.0
microsoft-extensions-configuration-fileextensions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-fileextensions_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-fileextensions_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-configuration-json_9-0-0: Microsoft.Extensions.Configuration.Json\nv9.0.0
microsoft-extensions-configuration-json_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-json_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-json_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-configuration-usersecrets_9-0-0: Microsoft.Extensions.Configuration.UserSecrets\nv9.0.0
microsoft-extensions-configuration-usersecrets_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-usersecrets_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration-usersecrets_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-configuration_9-0-0: Microsoft.Extensions.Configuration\nv9.0.0
microsoft-extensions-configuration_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration_9-0-0.style.opacity: 0.8
microsoft-extensions-configuration_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-dependencyinjection-abstractions_9-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.0
microsoft-extensions-dependencyinjection-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-dependencyinjection_9-0-0: Microsoft.Extensions.DependencyInjection\nv9.0.0
microsoft-extensions-dependencyinjection_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection_9-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-diagnostics_9-0-0: Microsoft.Extensions.Diagnostics\nv9.0.0
microsoft-extensions-diagnostics_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-diagnostics_9-0-0.style.opacity: 0.8
microsoft-extensions-diagnostics_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-fileproviders-abstractions_9-0-0: Microsoft.Extensions.FileProviders.Abstractions\nv9.0.0
microsoft-extensions-fileproviders-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-fileproviders-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-fileproviders-abstractions_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-fileproviders-physical_9-0-0: Microsoft.Extensions.FileProviders.Physical\nv9.0.0
microsoft-extensions-fileproviders-physical_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-fileproviders-physical_9-0-0.style.opacity: 0.8
microsoft-extensions-fileproviders-physical_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-hosting-abstractions_9-0-0: Microsoft.Extensions.Hosting.Abstractions\nv9.0.0
microsoft-extensions-hosting-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-hosting-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-hosting-abstractions_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-logging-abstractions_9-0-0: Microsoft.Extensions.Logging.Abstractions\nv9.0.0
microsoft-extensions-logging-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-logging-abstractions_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-logging-configuration_9-0-0: Microsoft.Extensions.Logging.Configuration\nv9.0.0
microsoft-extensions-logging-configuration_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-configuration_9-0-0.style.opacity: 0.8
microsoft-extensions-logging-configuration_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-logging-console_9-0-0: Microsoft.Extensions.Logging.Console\nv9.0.0
microsoft-extensions-logging-console_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-console_9-0-0.style.opacity: 0.8
microsoft-extensions-logging-console_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-logging-debug_9-0-0: Microsoft.Extensions.Logging.Debug\nv9.0.0
microsoft-extensions-logging-debug_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-debug_9-0-0.style.opacity: 0.8
microsoft-extensions-logging-debug_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-logging-eventlog_9-0-0: Microsoft.Extensions.Logging.EventLog\nv9.0.0
microsoft-extensions-logging-eventlog_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-eventlog_9-0-0.style.opacity: 0.8
microsoft-extensions-logging-eventlog_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-logging-eventsource_9-0-0: Microsoft.Extensions.Logging.EventSource\nv9.0.0
microsoft-extensions-logging-eventsource_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-eventsource_9-0-0.style.opacity: 0.8
microsoft-extensions-logging-eventsource_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-logging_9-0-0: Microsoft.Extensions.Logging\nv9.0.0
microsoft-extensions-logging_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging_9-0-0.style.opacity: 0.8
microsoft-extensions-logging_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-options_9-0-0: Microsoft.Extensions.Options\nv9.0.0
microsoft-extensions-options_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-options_9-0-0.style.opacity: 0.8
microsoft-extensions-options_9-0-0 <- microsoft-extensions-hosting_9-0-0
microsoft-extensions-hosting_9-0-0 <- aoi.alloverit-generichost
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-generichost
