direction: left

aoi: AllOverIt
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-lib-group: ""
amazon-cdk-lib-group.amazon-cdk-lib_2-223-0: Amazon.CDK.Lib\nv2.223.0
amazon-cdk-lib-group.amazon-cdk-lib_2-223-0.style.fill: "#ADD8E6"
amazon-cdk-lib-group.amazon-cdk-lib_2-223-0.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-242: Amazon.CDK.Asset.AwsCliV1\nv2.2.242
amazon-cdk-asset-awscliv1_2-2-242.style.fill: "#FFEC96"
amazon-cdk-asset-awscliv1_2-2-242.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-242 <- amazon-cdk-lib-group.amazon-cdk-lib_2-223-0
amazon-cdk-asset-nodeproxyagentv6_2-1-0: Amazon.CDK.Asset.NodeProxyAgentV6\nv2.1.0
amazon-cdk-asset-nodeproxyagentv6_2-1-0.style.fill: "#FFEC96"
amazon-cdk-asset-nodeproxyagentv6_2-1-0.style.opacity: 0.8
amazon-cdk-asset-nodeproxyagentv6_2-1-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-223-0
amazon-cdk-cloudassembly-schema_48-6-0: Amazon.CDK.CloudAssembly.Schema\nv48.6.0
amazon-cdk-cloudassembly-schema_48-6-0.style.fill: "#FFEC96"
amazon-cdk-cloudassembly-schema_48-6-0.style.opacity: 0.8
amazon-cdk-cloudassembly-schema_48-6-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-223-0
amazon-jsii-runtime-group: ""
amazon-jsii-runtime-group.amazon-jsii-runtime_1-118-0: Amazon.JSII.Runtime\nv1.118.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-118-0.style.fill: "#FFEC96"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-118-0.style.opacity: 0.8
amazon-jsii-runtime-group.amazon-jsii-runtime_1-118-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-223-0
constructs-group: ""
constructs-group.constructs_10-0-0: Constructs\nv10.0.0
constructs-group.constructs_10-0-0.style.fill: "#FFEC96"
constructs-group.constructs_10-0-0.style.opacity: 0.8
constructs-group.constructs_10-0-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-223-0
amazon-cdk-lib-group.amazon-cdk-lib_2-223-0 <- aoi.alloverit-aws-cdk-appsync
cdklabs-awscdkappsyncutils_0-0-858: Cdklabs.AwsCdkAppsyncUtils\nv0.0.858
cdklabs-awscdkappsyncutils_0-0-858.style.fill: "#ADD8E6"
cdklabs-awscdkappsyncutils_0-0-858.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0: Amazon.CDK.Lib\nv2.110.0
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.fill: "#FFEC96"
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0 <- cdklabs-awscdkappsyncutils_0-0-858
amazon-jsii-runtime-group.amazon-jsii-runtime_1-117-0: Amazon.JSII.Runtime\nv1.117.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-117-0.style.fill: "#FFEC96"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-117-0.style.opacity: 0.8
amazon-jsii-runtime-group.amazon-jsii-runtime_1-117-0 <- cdklabs-awscdkappsyncutils_0-0-858
constructs-group.constructs_10-0-5: Constructs\nv10.0.5
constructs-group.constructs_10-0-5.style.fill: "#FFEC96"
constructs-group.constructs_10-0-5.style.opacity: 0.8
constructs-group.constructs_10-0-5 <- cdklabs-awscdkappsyncutils_0-0-858
cdklabs-awscdkappsyncutils_0-0-858 <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
