direction: left

aoi: AllOverIt
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-lib-group: ""
amazon-cdk-lib-group.amazon-cdk-lib_2-171-0: Amazon.CDK.Lib\nv2.171.0
amazon-cdk-lib-group.amazon-cdk-lib_2-171-0.style.fill: "#ADD8E6"
amazon-cdk-lib-group.amazon-cdk-lib_2-171-0.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-208: Amazon.CDK.Asset.AwsCliV1\nv2.2.208
amazon-cdk-asset-awscliv1_2-2-208.style.fill: "#FFEC96"
amazon-cdk-asset-awscliv1_2-2-208.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-208 <- amazon-cdk-lib-group.amazon-cdk-lib_2-171-0
amazon-cdk-asset-kubectlv20_2-1-3: Amazon.CDK.Asset.KubectlV20\nv2.1.3
amazon-cdk-asset-kubectlv20_2-1-3.style.fill: "#FFEC96"
amazon-cdk-asset-kubectlv20_2-1-3.style.opacity: 0.8
amazon-cdk-asset-kubectlv20_2-1-3 <- amazon-cdk-lib-group.amazon-cdk-lib_2-171-0
amazon-cdk-asset-nodeproxyagentv6_2-1-0: Amazon.CDK.Asset.NodeProxyAgentV6\nv2.1.0
amazon-cdk-asset-nodeproxyagentv6_2-1-0.style.fill: "#FFEC96"
amazon-cdk-asset-nodeproxyagentv6_2-1-0.style.opacity: 0.8
amazon-cdk-asset-nodeproxyagentv6_2-1-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-171-0
amazon-cdk-cloudassembly-schema_38-0-1: Amazon.CDK.CloudAssembly.Schema\nv38.0.1
amazon-cdk-cloudassembly-schema_38-0-1.style.fill: "#FFEC96"
amazon-cdk-cloudassembly-schema_38-0-1.style.opacity: 0.8
amazon-cdk-cloudassembly-schema_38-0-1 <- amazon-cdk-lib-group.amazon-cdk-lib_2-171-0
amazon-jsii-runtime-group: ""
amazon-jsii-runtime-group.amazon-jsii-runtime_1-104-0: Amazon.JSII.Runtime\nv1.104.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-104-0.style.fill: "#FFEC96"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-104-0.style.opacity: 0.8
amazon-jsii-runtime-group.amazon-jsii-runtime_1-104-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-171-0
constructs-group: ""
constructs-group.constructs_10-0-0: Constructs\nv10.0.0
constructs-group.constructs_10-0-0.style.fill: "#FFEC96"
constructs-group.constructs_10-0-0.style.opacity: 0.8
constructs-group.constructs_10-0-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-171-0
amazon-cdk-lib-group.amazon-cdk-lib_2-171-0 <- aoi.alloverit-aws-cdk-appsync
cdklabs-awscdkappsyncutils_0-0-585: Cdklabs.AwsCdkAppsyncUtils\nv0.0.585
cdklabs-awscdkappsyncutils_0-0-585.style.fill: "#ADD8E6"
cdklabs-awscdkappsyncutils_0-0-585.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0: Amazon.CDK.Lib\nv2.110.0
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.fill: "#FFEC96"
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0 <- cdklabs-awscdkappsyncutils_0-0-585
amazon-jsii-runtime-group.amazon-jsii-runtime_1-105-0: Amazon.JSII.Runtime\nv1.105.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-105-0.style.fill: "#FFEC96"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-105-0.style.opacity: 0.8
amazon-jsii-runtime-group.amazon-jsii-runtime_1-105-0 <- cdklabs-awscdkappsyncutils_0-0-585
constructs-group.constructs_10-0-5: Constructs\nv10.0.5
constructs-group.constructs_10-0-5.style.fill: "#FFEC96"
constructs-group.constructs_10-0-5.style.opacity: 0.8
constructs-group.constructs_10-0-5 <- cdklabs-awscdkappsyncutils_0-0-585
cdklabs-awscdkappsyncutils_0-0-585 <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
