direction: left

aoi: AllOverIt
aoi.alloverit-serilog: AllOverIt.Serilog
microsoft-extensions-dependencyinjection-abstractions-group: ""
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_10-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv10.0.0
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_10-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_10-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_10-0-0 <- aoi.alloverit-serilog
microsoft-extensions-hosting-abstractions-group: ""
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0: Microsoft.Extensions.Hosting.Abstractions\nv10.0.0
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0.style.fill: "#ADD8E6"
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_10-0-0: Microsoft.Extensions.Configuration.Abstractions\nv10.0.0
microsoft-extensions-configuration-abstractions_10-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_10-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_10-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_10-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0
microsoft-extensions-diagnostics-abstractions_10-0-0: Microsoft.Extensions.Diagnostics.Abstractions\nv10.0.0
microsoft-extensions-diagnostics-abstractions_10-0-0.style.fill: "#FFEC96"
microsoft-extensions-diagnostics-abstractions_10-0-0.style.opacity: 0.8
microsoft-extensions-diagnostics-abstractions_10-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0
microsoft-extensions-fileproviders-abstractions_10-0-0: Microsoft.Extensions.FileProviders.Abstractions\nv10.0.0
microsoft-extensions-fileproviders-abstractions_10-0-0.style.fill: "#FFEC96"
microsoft-extensions-fileproviders-abstractions_10-0-0.style.opacity: 0.8
microsoft-extensions-fileproviders-abstractions_10-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0
microsoft-extensions-logging-abstractions-group: ""
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_10-0-0: Microsoft.Extensions.Logging.Abstractions\nv10.0.0
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_10-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_10-0-0.style.opacity: 0.8
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_10-0-0 <- microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_10-0-0 <- aoi.alloverit-serilog
serilog-extensions-hosting_9-0-0: Serilog.Extensions.Hosting\nv9.0.0
serilog-extensions-hosting_9-0-0.style.fill: "#ADD8E6"
serilog-extensions-hosting_9-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.0
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions-group.microsoft-extensions-dependencyinjection-abstractions_9-0-0 <- serilog-extensions-hosting_9-0-0
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0: Microsoft.Extensions.Hosting.Abstractions\nv9.0.0
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-hosting-abstractions-group.microsoft-extensions-hosting-abstractions_9-0-0 <- serilog-extensions-hosting_9-0-0
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_9-0-0: Microsoft.Extensions.Logging.Abstractions\nv9.0.0
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_9-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_9-0-0.style.opacity: 0.8
microsoft-extensions-logging-abstractions-group.microsoft-extensions-logging-abstractions_9-0-0 <- serilog-extensions-hosting_9-0-0
serilog_4-2-0: Serilog\nv4.2.0
serilog_4-2-0.style.fill: "#FFEC96"
serilog_4-2-0.style.opacity: 0.8
serilog_4-2-0 <- serilog-extensions-hosting_9-0-0
serilog-extensions-logging_9-0-0: Serilog.Extensions.Logging\nv9.0.0
serilog-extensions-logging_9-0-0.style.fill: "#FFEC96"
serilog-extensions-logging_9-0-0.style.opacity: 0.8
serilog-extensions-logging_9-0-0 <- serilog-extensions-hosting_9-0-0
serilog-extensions-hosting_9-0-0 <- aoi.alloverit-serilog
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-serilog
