direction: left

aoi: AllOverIt
aoi.alloverit-logging: AllOverIt.Logging
microsoft-extensions-logging-abstractions_10-0-7: Microsoft.Extensions.Logging.Abstractions\nv10.0.7
microsoft-extensions-logging-abstractions_10-0-7.style.fill: "#ADD8E6"
microsoft-extensions-logging-abstractions_10-0-7.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_10-0-7: Microsoft.Extensions.DependencyInjection.Abstractions\nv10.0.7
microsoft-extensions-dependencyinjection-abstractions_10-0-7.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions_10-0-7.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_10-0-7 <- microsoft-extensions-logging-abstractions_10-0-7
system-diagnostics-diagnosticsource_10-0-7: System.Diagnostics.DiagnosticSource\nv10.0.7
system-diagnostics-diagnosticsource_10-0-7.style.fill: "#FFEC96"
system-diagnostics-diagnosticsource_10-0-7.style.opacity: 0.8
system-diagnostics-diagnosticsource_10-0-7 <- microsoft-extensions-logging-abstractions_10-0-7
microsoft-extensions-logging-abstractions_10-0-7 <- aoi.alloverit-logging
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-logging
