direction: left

aoi: AllOverIt
aoi.alloverit-logging: AllOverIt.Logging
microsoft-extensions-logging-abstractions_9-0-1: Microsoft.Extensions.Logging.Abstractions\nv9.0.1
microsoft-extensions-logging-abstractions_9-0-1.style.fill: "#ADD8E6"
microsoft-extensions-logging-abstractions_9-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-1: Microsoft.Extensions.DependencyInjection.Abstractions\nv9.0.1
microsoft-extensions-dependencyinjection-abstractions_9-0-1.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions_9-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_9-0-1 <- microsoft-extensions-logging-abstractions_9-0-1
system-diagnostics-diagnosticsource_9-0-1: System.Diagnostics.DiagnosticSource\nv9.0.1
system-diagnostics-diagnosticsource_9-0-1.style.fill: "#FFEC96"
system-diagnostics-diagnosticsource_9-0-1.style.opacity: 0.8
system-diagnostics-diagnosticsource_9-0-1 <- microsoft-extensions-logging-abstractions_9-0-1
microsoft-extensions-logging-abstractions_9-0-1 <- aoi.alloverit-logging
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-logging
