direction: left

aoi: AllOverIt
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
microsoft-extensions-dependencyinjection-abstractions_8-0-1: Microsoft.Extensions.DependencyInjection.Abstractions\nv8.0.1
microsoft-extensions-dependencyinjection-abstractions_8-0-1.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_8-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_8-0-1 <- aoi.alloverit-reactiveui
reactiveui_20-1-1: ReactiveUI\nv20.1.1
reactiveui_20-1-1.style.fill: "#ADD8E6"
reactiveui_20-1-1.style.opacity: 0.8
dynamicdata_8-4-1: DynamicData\nv8.4.1
dynamicdata_8-4-1.style.fill: "#FFEC96"
dynamicdata_8-4-1.style.opacity: 0.8
dynamicdata_8-4-1 <- reactiveui_20-1-1
splat_15-1-1: Splat\nv15.1.1
splat_15-1-1.style.fill: "#FFEC96"
splat_15-1-1.style.opacity: 0.8
splat_15-1-1 <- reactiveui_20-1-1
system-componentmodel-annotations_5-0-0: System.ComponentModel.Annotations\nv5.0.0
system-componentmodel-annotations_5-0-0.style.fill: "#FFEC96"
system-componentmodel-annotations_5-0-0.style.opacity: 0.8
system-componentmodel-annotations_5-0-0 <- reactiveui_20-1-1
reactiveui_20-1-1 <- aoi.alloverit-reactiveui
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactiveui
