direction: left

aoi: AllOverIt
aoi.alloverit-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
microsoft-entityframeworkcore-relational_9-0-8: Microsoft.EntityFrameworkCore.Relational\nv9.0.8
microsoft-entityframeworkcore-relational_9-0-8.style.fill: "#ADD8E6"
microsoft-entityframeworkcore-relational_9-0-8.style.opacity: 0.8
microsoft-entityframeworkcore_9-0-8: Microsoft.EntityFrameworkCore\nv9.0.8
microsoft-entityframeworkcore_9-0-8.style.fill: "#FFEC96"
microsoft-entityframeworkcore_9-0-8.style.opacity: 0.8
microsoft-entityframeworkcore_9-0-8 <- microsoft-entityframeworkcore-relational_9-0-8
microsoft-extensions-configuration-abstractions_9-0-8: Microsoft.Extensions.Configuration.Abstractions\nv9.0.8
microsoft-extensions-configuration-abstractions_9-0-8.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_9-0-8.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_9-0-8 <- microsoft-entityframeworkcore-relational_9-0-8
microsoft-extensions-caching-memory_9-0-8: Microsoft.Extensions.Caching.Memory\nv9.0.8
microsoft-extensions-caching-memory_9-0-8.style.fill: "#FFEC96"
microsoft-extensions-caching-memory_9-0-8.style.opacity: 0.8
microsoft-extensions-caching-memory_9-0-8 <- microsoft-entityframeworkcore-relational_9-0-8
microsoft-extensions-logging_9-0-8: Microsoft.Extensions.Logging\nv9.0.8
microsoft-extensions-logging_9-0-8.style.fill: "#FFEC96"
microsoft-extensions-logging_9-0-8.style.opacity: 0.8
microsoft-extensions-logging_9-0-8 <- microsoft-entityframeworkcore-relational_9-0-8
microsoft-entityframeworkcore-relational_9-0-8 <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-entityframeworkcore-diagrams
