direction: left

aoi: AllOverIt
aoi.alloverit-fixture-fakeiteasy: AllOverIt.Fixture.FakeItEasy
autofixture-autofakeiteasy_4-18-1: AutoFixture.AutoFakeItEasy\nv4.18.1
autofixture-autofakeiteasy_4-18-1.style.fill: "#ADD8E6"
autofixture-autofakeiteasy_4-18-1.style.opacity: 0.8
autofixture_4-18-1: AutoFixture\nv4.18.1
autofixture_4-18-1.style.opacity: 0.8
autofixture_4-18-1.style.fill: "#ADD8E6"
autofixture_4-18-1 <- autofixture-autofakeiteasy_4-18-1
fakeiteasy-group: ""
fakeiteasy-group.fakeiteasy_4-9-0: FakeItEasy\nv4.9.0
fakeiteasy-group.fakeiteasy_4-9-0.style.fill: "#FFEC96"
fakeiteasy-group.fakeiteasy_4-9-0.style.opacity: 0.8
fakeiteasy-group.fakeiteasy_4-9-0 <- autofixture-autofakeiteasy_4-18-1
autofixture-autofakeiteasy_4-18-1 <- aoi.alloverit-fixture-fakeiteasy
fakeiteasy-group.fakeiteasy_8-3-0: FakeItEasy\nv8.3.0
fakeiteasy-group.fakeiteasy_8-3-0.style.fill: "#ADD8E6"
fakeiteasy-group.fakeiteasy_8-3-0.style.opacity: 0.8
castle-core_5-1-1: Castle.Core\nv5.1.1
castle-core_5-1-1.style.fill: "#FFEC96"
castle-core_5-1-1.style.opacity: 0.8
castle-core_5-1-1 <- fakeiteasy-group.fakeiteasy_8-3-0
fakeiteasy-group.fakeiteasy_8-3-0 <- aoi.alloverit-fixture-fakeiteasy
aoi.alloverit-fixture: AllOverIt.Fixture
fare_2-1-1: Fare\nv2.1.1
fare_2-1-1.style.fill: "#FFEC96"
fare_2-1-1.style.opacity: 0.8
fare_2-1-1 <- autofixture_4-18-1
system-componentmodel-annotations_4-3-0: System.ComponentModel.Annotations\nv4.3.0
system-componentmodel-annotations_4-3-0.style.fill: "#FFEC96"
system-componentmodel-annotations_4-3-0.style.opacity: 0.8
system-componentmodel-annotations_4-3-0 <- autofixture_4-18-1
autofixture_4-18-1 <- aoi.alloverit-fixture
fluentassertions_6-12-2: FluentAssertions\nv6.12.2
fluentassertions_6-12-2.style.fill: "#ADD8E6"
fluentassertions_6-12-2.style.opacity: 0.8
system-configuration-configurationmanager_4-4-0: System.Configuration.ConfigurationManager\nv4.4.0
system-configuration-configurationmanager_4-4-0.style.fill: "#FFEC96"
system-configuration-configurationmanager_4-4-0.style.opacity: 0.8
system-configuration-configurationmanager_4-4-0 <- fluentassertions_6-12-2
fluentassertions_6-12-2 <- aoi.alloverit-fixture
nsubstitute_5-3-0: NSubstitute\nv5.3.0
nsubstitute_5-3-0.style.fill: "#ADD8E6"
nsubstitute_5-3-0.style.opacity: 0.8
castle-core_5-1-1 <- nsubstitute_5-3-0
nsubstitute_5-3-0 <- aoi.alloverit-fixture
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-fixture
aoi.alloverit-fixture <- aoi.alloverit-fixture-fakeiteasy
