direction: left

aoi: AllOverIt
aoi.alloverit-entityframeworkcore-pagination: AllOverIt.EntityFrameworkCore.Pagination
aoi.alloverit-entityframeworkcore: AllOverIt.EntityFrameworkCore
microsoft-entityframeworkcore-relational_9-0-11: Microsoft.EntityFrameworkCore.Relational\nv9.0.11
microsoft-entityframeworkcore-relational_9-0-11.style.fill: "#ADD8E6"
microsoft-entityframeworkcore-relational_9-0-11.style.opacity: 0.8
microsoft-entityframeworkcore_9-0-11: Microsoft.EntityFrameworkCore\nv9.0.11
microsoft-entityframeworkcore_9-0-11.style.fill: "#FFEC96"
microsoft-entityframeworkcore_9-0-11.style.opacity: 0.8
microsoft-entityframeworkcore_9-0-11 <- microsoft-entityframeworkcore-relational_9-0-11
microsoft-extensions-configuration-abstractions_9-0-11: Microsoft.Extensions.Configuration.Abstractions\nv9.0.11
microsoft-extensions-configuration-abstractions_9-0-11.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_9-0-11.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_9-0-11 <- microsoft-entityframeworkcore-relational_9-0-11
microsoft-extensions-caching-memory_9-0-11: Microsoft.Extensions.Caching.Memory\nv9.0.11
microsoft-extensions-caching-memory_9-0-11.style.fill: "#FFEC96"
microsoft-extensions-caching-memory_9-0-11.style.opacity: 0.8
microsoft-extensions-caching-memory_9-0-11 <- microsoft-entityframeworkcore-relational_9-0-11
microsoft-extensions-logging_9-0-11: Microsoft.Extensions.Logging\nv9.0.11
microsoft-extensions-logging_9-0-11.style.fill: "#FFEC96"
microsoft-extensions-logging_9-0-11.style.opacity: 0.8
microsoft-extensions-logging_9-0-11 <- microsoft-entityframeworkcore-relational_9-0-11
microsoft-entityframeworkcore-relational_9-0-11 <- aoi.alloverit-entityframeworkcore
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-entityframeworkcore
aoi.alloverit-entityframeworkcore <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-pagination: AllOverIt.Pagination
microsoft-extensions-dependencyinjection-abstractions_10-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv10.0.0
microsoft-extensions-dependencyinjection-abstractions_10-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_10-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_10-0-0 <- aoi.alloverit-pagination
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit-serialization-binary <- aoi.alloverit-pagination
aoi.alloverit-pagination <- aoi.alloverit-entityframeworkcore-pagination
