direction: left

aoi: AllOverIt
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-lib-group: ""
amazon-cdk-lib-group.amazon-cdk-lib_2-251-0: Amazon.CDK.Lib\nv2.251.0
amazon-cdk-lib-group.amazon-cdk-lib_2-251-0.style.fill: "#ADD8E6"
amazon-cdk-lib-group.amazon-cdk-lib_2-251-0.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-273: Amazon.CDK.Asset.AwsCliV1\nv2.2.273
amazon-cdk-asset-awscliv1_2-2-273.style.fill: "#FFEC96"
amazon-cdk-asset-awscliv1_2-2-273.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-273 <- amazon-cdk-lib-group.amazon-cdk-lib_2-251-0
amazon-cdk-asset-nodeproxyagentv6_2-1-1: Amazon.CDK.Asset.NodeProxyAgentV6\nv2.1.1
amazon-cdk-asset-nodeproxyagentv6_2-1-1.style.fill: "#FFEC96"
amazon-cdk-asset-nodeproxyagentv6_2-1-1.style.opacity: 0.8
amazon-cdk-asset-nodeproxyagentv6_2-1-1 <- amazon-cdk-lib-group.amazon-cdk-lib_2-251-0
amazon-cdk-cloudassembly-schema_53-18-0: Amazon.CDK.CloudAssembly.Schema\nv53.18.0
amazon-cdk-cloudassembly-schema_53-18-0.style.fill: "#FFEC96"
amazon-cdk-cloudassembly-schema_53-18-0.style.opacity: 0.8
amazon-cdk-cloudassembly-schema_53-18-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-251-0
amazon-jsii-runtime-group: ""
amazon-jsii-runtime-group.amazon-jsii-runtime_1-127-0: Amazon.JSII.Runtime\nv1.127.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-127-0.style.fill: "#FFEC96"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-127-0.style.opacity: 0.8
amazon-jsii-runtime-group.amazon-jsii-runtime_1-127-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-251-0
constructs-group: ""
constructs-group.constructs_10-5-0: Constructs\nv10.5.0
constructs-group.constructs_10-5-0.style.fill: "#FFEC96"
constructs-group.constructs_10-5-0.style.opacity: 0.8
constructs-group.constructs_10-5-0 <- amazon-cdk-lib-group.amazon-cdk-lib_2-251-0
amazon-cdk-lib-group.amazon-cdk-lib_2-251-0 <- aoi.alloverit-aws-cdk-appsync
amazon-jsii-runtime-group.amazon-jsii-runtime_1-128-0: Amazon.JSII.Runtime\nv1.128.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-128-0.style.fill: "#ADD8E6"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-128-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection_9-0-1: Microsoft.Extensions.DependencyInjection\nv9.0.1
microsoft-extensions-dependencyinjection_9-0-1.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection_9-0-1.style.opacity: 0.8
microsoft-extensions-dependencyinjection_9-0-1 <- amazon-jsii-runtime-group.amazon-jsii-runtime_1-128-0
microsoft-extensions-logging_9-0-1: Microsoft.Extensions.Logging\nv9.0.1
microsoft-extensions-logging_9-0-1.style.fill: "#FFEC96"
microsoft-extensions-logging_9-0-1.style.opacity: 0.8
microsoft-extensions-logging_9-0-1 <- amazon-jsii-runtime-group.amazon-jsii-runtime_1-128-0
microsoft-extensions-logging-console_9-0-1: Microsoft.Extensions.Logging.Console\nv9.0.1
microsoft-extensions-logging-console_9-0-1.style.fill: "#FFEC96"
microsoft-extensions-logging-console_9-0-1.style.opacity: 0.8
microsoft-extensions-logging-console_9-0-1 <- amazon-jsii-runtime-group.amazon-jsii-runtime_1-128-0
newtonsoft-json_13-0-3: Newtonsoft.Json\nv13.0.3
newtonsoft-json_13-0-3.style.fill: "#FFEC96"
newtonsoft-json_13-0-3.style.opacity: 0.8
newtonsoft-json_13-0-3 <- amazon-jsii-runtime-group.amazon-jsii-runtime_1-128-0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-128-0 <- aoi.alloverit-aws-cdk-appsync
cdklabs-awscdkappsyncutils_0-0-858: Cdklabs.AwsCdkAppsyncUtils\nv0.0.858
cdklabs-awscdkappsyncutils_0-0-858.style.fill: "#ADD8E6"
cdklabs-awscdkappsyncutils_0-0-858.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0: Amazon.CDK.Lib\nv2.110.0
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.fill: "#FFEC96"
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0.style.opacity: 0.8
amazon-cdk-lib-group.amazon-cdk-lib_2-110-0 <- cdklabs-awscdkappsyncutils_0-0-858
amazon-jsii-runtime-group.amazon-jsii-runtime_1-117-0: Amazon.JSII.Runtime\nv1.117.0
amazon-jsii-runtime-group.amazon-jsii-runtime_1-117-0.style.fill: "#FFEC96"
amazon-jsii-runtime-group.amazon-jsii-runtime_1-117-0.style.opacity: 0.8
amazon-jsii-runtime-group.amazon-jsii-runtime_1-117-0 <- cdklabs-awscdkappsyncutils_0-0-858
constructs-group.constructs_10-0-5: Constructs\nv10.0.5
constructs-group.constructs_10-0-5.style.fill: "#FFEC96"
constructs-group.constructs_10-0-5.style.opacity: 0.8
constructs-group.constructs_10-0-5 <- cdklabs-awscdkappsyncutils_0-0-858
cdklabs-awscdkappsyncutils_0-0-858 <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
