direction: left

aoi: AllOverIt
aoi.alloverit-wpf-controls: AllOverIt.Wpf.Controls
microsoft-xaml-behaviors-wpf_1-1-135: Microsoft.Xaml.Behaviors.Wpf\nv1.1.135
microsoft-xaml-behaviors-wpf_1-1-135.style.fill: "#ADD8E6"
microsoft-xaml-behaviors-wpf_1-1-135.style.opacity: 0.8
microsoft-xaml-behaviors-wpf_1-1-135 <- aoi.alloverit-wpf-controls
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-wpf-controls
