direction: left

aoi: AllOverIt
aoi.alloverit-reactiveui-wpf: AllOverIt.ReactiveUI.Wpf
reactiveui-wpf_22-2-1: ReactiveUI.WPF\nv22.2.1
reactiveui-wpf_22-2-1.style.fill: "#ADD8E6"
reactiveui-wpf_22-2-1.style.opacity: 0.8
reactiveui-wpf_22-2-1 <- aoi.alloverit-reactiveui-wpf
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
microsoft-extensions-dependencyinjection-abstractions_10-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv10.0.0
microsoft-extensions-dependencyinjection-abstractions_10-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_10-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_10-0-0 <- aoi.alloverit-reactiveui
reactiveui_22-2-1: ReactiveUI\nv22.2.1
reactiveui_22-2-1.style.fill: "#ADD8E6"
reactiveui_22-2-1.style.opacity: 0.8
dynamicdata_9-4-1: DynamicData\nv9.4.1
dynamicdata_9-4-1.style.fill: "#FFEC96"
dynamicdata_9-4-1.style.opacity: 0.8
dynamicdata_9-4-1 <- reactiveui_22-2-1
splat_17-1-1: Splat\nv17.1.1
splat_17-1-1.style.fill: "#FFEC96"
splat_17-1-1.style.opacity: 0.8
splat_17-1-1 <- reactiveui_22-2-1
system-reactive_6-1-0: System.Reactive\nv6.1.0
system-reactive_6-1-0.style.fill: "#FFEC96"
system-reactive_6-1-0.style.opacity: 0.8
system-reactive_6-1-0 <- reactiveui_22-2-1
reactiveui_22-2-1 <- aoi.alloverit-reactiveui
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactiveui
aoi.alloverit-reactiveui <- aoi.alloverit-reactiveui-wpf
