flowchart LR
  alloverit-validation["AllOverIt.Validation"]
  fluentvalidation_12-1-1["FluentValidation<br>v12.1.1"]
  microsoft-extensions-dependencyinjection-abstractions_10-0-8["Microsoft.Extensions.DependencyInjection.Abstractions<br>v10.0.8"]
  alloverit["AllOverIt"]
  alloverit-assertion["AllOverIt.Assertion"]
  alloverit-validation --> fluentvalidation_12-1-1
  alloverit-validation --> microsoft-extensions-dependencyinjection-abstractions_10-0-8
  alloverit-validation --> alloverit
  alloverit --> alloverit-assertion
  style fluentvalidation_12-1-1 fill:#ADD8E6,opacity:0.8
  style microsoft-extensions-dependencyinjection-abstractions_10-0-8 fill:#ADD8E6,opacity:0.8
